[staging]
ENCRYPTION_KEY = "secret"
DATABASE_URL_UNPOOLED = "postgresql://neondb_owner:npg_myb3xXiKpI0s@ep-lively-darkness-ac9jxoyz.sa-east-1.aws.neon.tech/neondb?sslmode=require"
DATABASE_URL = "postgres://neondb_owner:npg_myb3xXiKpI0s@ep-lively-darkness-ac9jxoyz-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require"
DATABASE_HOST = "ep-lively-darkness-ac9jxoyz-pooler.sa-east-1.aws.neon.tech"
DATABASE_NAME = "neondb"
DATABASE_USER = "neondb_owner"
DATABASE_PASSWORD = "npg_myb3xXiKpI0s"
STORAGE_SERVICE_URI = "https://storage.googleapis.com"
STORAGE_SERVICE_KEY = "secret"
EXEC_MODE = "staging"
DEBUG = false
PORT = 8080
STATUS_CODES = {"disabled": 0, "enabled": 1, "deleted": 2, "blocked": 3, "pending": 4, "accepted": 5, "ignored": 6, "unread": 7, "read": 8, "banned": 9}

[development]
ENCRYPTION_KEY = "secret"
DATABASE_URL = "postgres://neondb_owner:npg_myb3xXiKpI0s@ep-lively-darkness-ac9jxoyz-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require"
DATABASE_URL_UNPOOLED = "postgresql://neondb_owner:npg_myb3xXiKpI0s@ep-lively-darkness-ac9jxoyz.sa-east-1.aws.neon.tech/neondb?sslmode=require"
DATABASE_HOST = "ep-lively-darkness-ac9jxoyz-pooler.sa-east-1.aws.neon.tech"
DATABASE_NAME = "neondb"
DATABASE_USER = "neondb_owner"
DATABASE_PASSWORD = "npg_myb3xXiKpI0s"
STORAGE_SERVICE_URI = "https://storage.googleapis.com"
STORAGE_SERVICE_KEY = "secret"
EXEC_MODE = "dev"
DEBUG = false
PORT = 8080
STATUS_CODES = {"disabled": 0, "enabled": 1, "deleted": 2, "blocked": 3, "pending": 4, "accepted": 5, "ignored": 6, "unread": 7, "read": 8, "banned": 9}


[production]
ENCRYPTION_KEY = "secret"
DATABASE_URL = "postgres://neondb_owner:npg_myb3xXiKpI0s@ep-lively-darkness-ac9jxoyz-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require"
DATABASE_URL_UNPOOLED = "postgresql://neondb_owner:npg_myb3xXiKpI0s@ep-lively-darkness-ac9jxoyz.sa-east-1.aws.neon.tech/neondb?sslmode=require"
DATABASE_HOST = "ep-lively-darkness-ac9jxoyz-pooler.sa-east-1.aws.neon.tech"
DATABASE_NAME = "neondb"
DATABASE_USER = "neondb_owner"
DATABASE_PASSWORD = "npg_myb3xXiKpI0s"
STORAGE_SERVICE_URI = "https://storage.googleapis.com"
STORAGE_SERVICE_KEY = "secret"
EXEC_MODE = "prod"
DEBUG = false
PORT = 8080
STATUS_CODES = {"disabled": 0, "enabled": 1, "deleted": 2, "blocked": 3, "pending": 4, "accepted": 5, "ignored": 6, "unread": 7, "read": 8}