"""baseline schema

Revision ID: c0781a0a5605
Revises: 
Create Date: 2026-08-20 16:31:44.349273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'c0781a0a5605'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_0',
    sa.Column('cl_0a', sa.String(), nullable=False),
    sa.Column('cl_0b', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=False),
    sa.Column('cl_0b_h', sa.String(length=64), nullable=False),
    sa.Column('cl_0c', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=False),
    sa.Column('cl_0c_h', sa.String(length=64), nullable=False),
    sa.Column('cl_0d', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=True),
    sa.Column('cl_0e', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cl_0a'),
    sa.UniqueConstraint('cl_0b_h'),
    sa.UniqueConstraint('cl_0c_h')
    )
    op.create_table('tb_5',
    sa.Column('cl_5a', sa.UUID(), nullable=False),
    sa.Column('cl_5b', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=False),
    sa.Column('cl_5c', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=False),
    # Gerada a partir dos models atuais, onde já é Integer. Aqui fica
    # DateTime de propósito: 20260812_01 é quem faz essa conversão, e
    # ela roda logo depois desta. Os bancos que já existem estão
    # carimbados naquela revisão, então precisam chegar no mesmo
    # estado por este caminho.
    sa.Column('cl_5d', sa.DateTime(), nullable=False),
    sa.Column('cl_5e', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=False),
    sa.Column('cl_5f', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cl_5a')
    )
    op.create_table('tb_1',
    sa.Column('cl_1a', sa.UUID(), nullable=False),
    sa.Column('cl_1b', sa.String(), nullable=False),
    sa.Column('cl_1c', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=False),
    sa.Column('cl_1d', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=True),
    sa.Column('cl_1e', sa.Integer(), nullable=False),
    sa.Column('cl_1f', sa.Boolean(), nullable=False),
    sa.Column('cl_1g', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cl_1b'], ['tb_0.cl_0a'], ),
    sa.PrimaryKeyConstraint('cl_1a')
    )
    op.create_table('tb_2',
    sa.Column('cl_2a', sa.UUID(), nullable=False),
    sa.Column('cl_2b', sa.String(), nullable=False),
    sa.Column('cl_2c', sa.String(), nullable=False),
    sa.Column('cl_2f', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cl_2b'], ['tb_0.cl_0a'], ),
    sa.ForeignKeyConstraint(['cl_2c'], ['tb_0.cl_0a'], ),
    sa.PrimaryKeyConstraint('cl_2a')
    )
    op.create_table('tb_3',
    sa.Column('cl_3a', sa.UUID(), nullable=False),
    sa.Column('cl_3b', sa.String(), nullable=False),
    sa.Column('cl_3c', sa.String(), nullable=False),
    sa.Column('cl_3d', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=False),
    sa.Column('cl_3e', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=True),
    sa.Column('cl_3f', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cl_3b'], ['tb_0.cl_0a'], ),
    sa.ForeignKeyConstraint(['cl_3c'], ['tb_0.cl_0a'], ),
    sa.PrimaryKeyConstraint('cl_3a')
    )
    op.create_table('tb_6',
    sa.Column('cl_6a', sa.UUID(), nullable=False),
    sa.Column('cl_6b', sa.String(), nullable=False),
    sa.Column('cl_6c', sa.UUID(), nullable=False),
    sa.Column('cl_6d', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=False),
    sa.Column('cl_6e', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cl_6b'], ['tb_0.cl_0a'], ),
    sa.ForeignKeyConstraint(['cl_6c'], ['tb_5.cl_5a'], ),
    sa.PrimaryKeyConstraint('cl_6a')
    )
    op.create_table('tb_7',
    sa.Column('cl_7a', sa.UUID(), nullable=False),
    sa.Column('cl_7b', sa.Integer(), nullable=False),
    sa.Column('cl_7c', sa.String(), nullable=True),
    sa.Column('cl_7d', sa.Integer(), nullable=True),
    sa.Column('cl_7e', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cl_7c'], ['tb_0.cl_0a'], ),
    sa.PrimaryKeyConstraint('cl_7a')
    )
    op.create_table('tb_8',
    sa.Column('cl_8a', sa.UUID(), nullable=False),
    sa.Column('cl_8b', sa.String(), nullable=False),
    sa.Column('cl_8c', sa.Text(), nullable=False),
    sa.Column('cl_8d', sa.DateTime(), nullable=False),
    sa.Column('cl_8e', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cl_8b'], ['tb_0.cl_0a'], ),
    sa.PrimaryKeyConstraint('cl_8a'),
    sa.UniqueConstraint('cl_8c')
    )
    op.create_index(op.f('ix_tb_8_cl_8b'), 'tb_8', ['cl_8b'], unique=False)
    op.create_table('tb_9',
    sa.Column('cl_9a', sa.UUID(), nullable=False),
    sa.Column('cl_9b', sa.String(), nullable=False),
    sa.Column('cl_9c', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=False),
    sa.Column('cl_9c_h', sa.String(length=64), nullable=False),
    sa.Column('cl_9d', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cl_9b'], ['tb_0.cl_0a'], ),
    sa.PrimaryKeyConstraint('cl_9a')
    )
    op.create_index(op.f('ix_tb_9_cl_9c_h'), 'tb_9', ['cl_9c_h'], unique=False)
    op.create_table('tb_4',
    sa.Column('cl_4a', sa.UUID(), nullable=False),
    sa.Column('cl_4b', sa.UUID(), nullable=False),
    sa.Column('cl_4c', sa.String(), nullable=False),
    sa.Column('cl_4d', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=False),
    sa.Column('cl_4e', sa.Integer(), nullable=False),
    sa.Column('cl_4f', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=False),
    sa.Column('cl_4g', sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cl_4b'], ['tb_3.cl_3a'], ),
    sa.ForeignKeyConstraint(['cl_4c'], ['tb_0.cl_0a'], ),
    sa.PrimaryKeyConstraint('cl_4a')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_4')
    op.drop_index(op.f('ix_tb_9_cl_9c_h'), table_name='tb_9')
    op.drop_table('tb_9')
    op.drop_index(op.f('ix_tb_8_cl_8b'), table_name='tb_8')
    op.drop_table('tb_8')
    op.drop_table('tb_7')
    op.drop_table('tb_6')
    op.drop_table('tb_3')
    op.drop_table('tb_2')
    op.drop_table('tb_1')
    op.drop_table('tb_5')
    op.drop_table('tb_0')
    # ### end Alembic commands ###
