"""add username and email hash columns

Revision ID: e8a18a96f538
Revises: dd9051ae5321
Create Date: 2026-05-28 16:27:34.888217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8a18a96f538'
down_revision: Union[str, None] = 'dd9051ae5321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_4')
    op.drop_table('tbl_2')
    op.drop_index(op.f('ix_tbl_1_col_b2_hash'), table_name='tbl_1')
    op.drop_index(op.f('ix_tbl_1_col_b4_hash'), table_name='tbl_1')
    op.drop_table('tbl_1')
    op.drop_table('tbl_3')
    op.drop_index(op.f('ix_tbl_0_col_a1_hash'), table_name='tbl_0')
    op.drop_table('tbl_0')
    op.alter_column('tb_0', 'cl_0d',
               existing_type=postgresql.BYTEA(),
               type_=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               nullable=True)
    op.drop_index(op.f('ix_tb_0_cl_0b_h'), table_name='tb_0')
    op.drop_index(op.f('ix_tb_0_cl_0c_h'), table_name='tb_0')
    op.drop_index(op.f('ix_tb_0_cl_0d_h'), table_name='tb_0')
    op.drop_constraint(op.f('tb_0_cl_0b_key'), 'tb_0', type_='unique')
    op.drop_constraint(op.f('tb_0_cl_0c_key'), 'tb_0', type_='unique')
    op.create_unique_constraint(None, 'tb_0', ['cl_0c_h'])
    op.create_unique_constraint(None, 'tb_0', ['cl_0b_h'])
    op.drop_column('tb_0', 'cl_0d_h')
    op.alter_column('tb_1', 'cl_1c',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               existing_nullable=False)
    op.alter_column('tb_1', 'cl_1d',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               nullable=True)
    op.drop_index(op.f('ix_tb_1_cl_1c_h'), table_name='tb_1')
    op.drop_index(op.f('ix_tb_1_cl_1d_h'), table_name='tb_1')
    op.drop_column('tb_1', 'cl_1c_h')
    op.drop_column('tb_1', 'cl_1d_h')
    op.alter_column('tb_2', 'cl_2d',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               existing_nullable=False)
    op.alter_column('tb_2', 'cl_2e',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               existing_nullable=False)
    op.drop_index(op.f('ix_tb_2_cl_2d_h'), table_name='tb_2')
    op.drop_index(op.f('ix_tb_2_cl_2e_h'), table_name='tb_2')
    op.drop_column('tb_2', 'cl_2d_h')
    op.drop_column('tb_2', 'cl_2e_h')
    op.alter_column('tb_3', 'cl_3d',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               existing_nullable=False)
    op.alter_column('tb_3', 'cl_3e',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               nullable=True)
    op.drop_index(op.f('ix_tb_3_cl_3d_h'), table_name='tb_3')
    op.drop_index(op.f('ix_tb_3_cl_3e_h'), table_name='tb_3')
    op.drop_column('tb_3', 'cl_3e_h')
    op.drop_column('tb_3', 'cl_3d_h')
    op.alter_column('tb_4', 'cl_4d',
               existing_type=sa.TEXT(),
               type_=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               existing_nullable=False)
    op.alter_column('tb_4', 'cl_4f',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               existing_nullable=False)
    op.alter_column('tb_4', 'cl_4g',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               nullable=True)
    op.drop_index(op.f('ix_tb_4_cl_4d_h'), table_name='tb_4')
    op.drop_index(op.f('ix_tb_4_cl_4f_h'), table_name='tb_4')
    op.drop_index(op.f('ix_tb_4_cl_4g_h'), table_name='tb_4')
    op.drop_column('tb_4', 'cl_4f_h')
    op.drop_column('tb_4', 'cl_4d_h')
    op.drop_column('tb_4', 'cl_4g_h')
    op.alter_column('tb_5', 'cl_5c',
               existing_type=sa.TEXT(),
               type_=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               existing_nullable=False)
    op.alter_column('tb_5', 'cl_5e',
               existing_type=postgresql.BYTEA(),
               type_=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               existing_nullable=False)
    op.drop_index(op.f('ix_tb_5_cl_5b_h'), table_name='tb_5')
    op.drop_index(op.f('ix_tb_5_cl_5c_h'), table_name='tb_5')
    op.drop_index(op.f('ix_tb_5_cl_5d_h'), table_name='tb_5')
    op.drop_index(op.f('ix_tb_5_cl_5e_h'), table_name='tb_5')
    op.drop_column('tb_5', 'cl_5c_h')
    op.drop_column('tb_5', 'cl_5b_h')
    op.drop_column('tb_5', 'cl_5d_h')
    op.drop_column('tb_5', 'cl_5e_h')
    op.alter_column('tb_6', 'cl_6d',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               existing_nullable=False)
    op.drop_index(op.f('ix_tb_6_cl_6d_h'), table_name='tb_6')
    op.drop_column('tb_6', 'cl_6d_h')
    op.alter_column('tb_7', 'cl_7e',
               existing_type=sa.TEXT(),
               type_=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_7', 'cl_7e',
               existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('tb_6', sa.Column('cl_6d_h', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_tb_6_cl_6d_h'), 'tb_6', ['cl_6d_h'], unique=False)
    op.alter_column('tb_6', 'cl_6d',
               existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.add_column('tb_5', sa.Column('cl_5e_h', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('tb_5', sa.Column('cl_5d_h', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('tb_5', sa.Column('cl_5b_h', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('tb_5', sa.Column('cl_5c_h', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_tb_5_cl_5e_h'), 'tb_5', ['cl_5e_h'], unique=False)
    op.create_index(op.f('ix_tb_5_cl_5d_h'), 'tb_5', ['cl_5d_h'], unique=False)
    op.create_index(op.f('ix_tb_5_cl_5c_h'), 'tb_5', ['cl_5c_h'], unique=False)
    op.create_index(op.f('ix_tb_5_cl_5b_h'), 'tb_5', ['cl_5b_h'], unique=False)
    op.alter_column('tb_5', 'cl_5e',
               existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               type_=postgresql.BYTEA(),
               existing_nullable=False)
    op.alter_column('tb_5', 'cl_5c',
               existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('tb_4', sa.Column('cl_4g_h', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('tb_4', sa.Column('cl_4d_h', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('tb_4', sa.Column('cl_4f_h', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_tb_4_cl_4g_h'), 'tb_4', ['cl_4g_h'], unique=False)
    op.create_index(op.f('ix_tb_4_cl_4f_h'), 'tb_4', ['cl_4f_h'], unique=False)
    op.create_index(op.f('ix_tb_4_cl_4d_h'), 'tb_4', ['cl_4d_h'], unique=False)
    op.alter_column('tb_4', 'cl_4g',
               existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tb_4', 'cl_4f',
               existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('tb_4', 'cl_4d',
               existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('tb_3', sa.Column('cl_3d_h', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('tb_3', sa.Column('cl_3e_h', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_tb_3_cl_3e_h'), 'tb_3', ['cl_3e_h'], unique=False)
    op.create_index(op.f('ix_tb_3_cl_3d_h'), 'tb_3', ['cl_3d_h'], unique=False)
    op.alter_column('tb_3', 'cl_3e',
               existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tb_3', 'cl_3d',
               existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.add_column('tb_2', sa.Column('cl_2e_h', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('tb_2', sa.Column('cl_2d_h', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_tb_2_cl_2e_h'), 'tb_2', ['cl_2e_h'], unique=False)
    op.create_index(op.f('ix_tb_2_cl_2d_h'), 'tb_2', ['cl_2d_h'], unique=False)
    op.alter_column('tb_2', 'cl_2e',
               existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('tb_2', 'cl_2d',
               existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.add_column('tb_1', sa.Column('cl_1d_h', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('tb_1', sa.Column('cl_1c_h', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_tb_1_cl_1d_h'), 'tb_1', ['cl_1d_h'], unique=False)
    op.create_index(op.f('ix_tb_1_cl_1c_h'), 'tb_1', ['cl_1c_h'], unique=False)
    op.alter_column('tb_1', 'cl_1d',
               existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tb_1', 'cl_1c',
               existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.add_column('tb_0', sa.Column('cl_0d_h', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tb_0', type_='unique')
    op.drop_constraint(None, 'tb_0', type_='unique')
    op.create_unique_constraint(op.f('tb_0_cl_0c_key'), 'tb_0', ['cl_0c'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('tb_0_cl_0b_key'), 'tb_0', ['cl_0b'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_tb_0_cl_0d_h'), 'tb_0', ['cl_0d_h'], unique=False)
    op.create_index(op.f('ix_tb_0_cl_0c_h'), 'tb_0', ['cl_0c_h'], unique=True)
    op.create_index(op.f('ix_tb_0_cl_0b_h'), 'tb_0', ['cl_0b_h'], unique=True)
    op.alter_column('tb_0', 'cl_0d',
               existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
               type_=postgresql.BYTEA(),
               nullable=False)
    op.create_table('tbl_3',
    sa.Column('col_d0', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('col_d1', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('col_d2', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['col_d2'], ['tbl_0.col_a0'], name=op.f('tbl_3_col_d2_fkey')),
    sa.PrimaryKeyConstraint('col_d0', name=op.f('tbl_3_pkey'))
    )
    op.create_table('tbl_2',
    sa.Column('col_c0', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('col_c1', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('col_c2', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('col_c3', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('col_c4', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('col_c5', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('col_c6', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('col_c7', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('col_c8', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('col_c9', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('col_c10', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['col_c1'], ['tbl_1.col_b0'], name=op.f('tbl_2_col_c1_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('col_c0', name=op.f('tbl_2_pkey'))
    )
    op.create_table('tbl_4',
    sa.Column('col_e0', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('col_e1', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['col_e0'], ['tbl_1.col_b0'], name=op.f('tbl_4_col_e0_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['col_e1'], ['tbl_3.col_d0'], name=op.f('tbl_4_col_e1_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('col_e0', 'col_e1', name=op.f('tbl_4_pkey'))
    )
    op.create_table('tbl_0',
    sa.Column('col_a0', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('col_a1', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('col_a1_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('col_a2', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('col_a3', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('col_a4', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('col_a5', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('col_a6', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('col_a0', name=op.f('tbl_0_pkey')),
    sa.UniqueConstraint('col_a1', name=op.f('tbl_0_col_a1_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_tbl_0_col_a1_hash'), 'tbl_0', ['col_a1_hash'], unique=True)
    op.create_table('tbl_1',
    sa.Column('col_b0', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('col_b1', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('col_b2', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('col_b2_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('col_b3', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('col_b4', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('col_b4_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('col_b5', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('col_b6', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('col_b7', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['col_b1'], ['tbl_0.col_a0'], name=op.f('tbl_1_col_b1_fkey')),
    sa.PrimaryKeyConstraint('col_b0', name=op.f('tbl_1_pkey'))
    )
    op.create_index(op.f('ix_tbl_1_col_b4_hash'), 'tbl_1', ['col_b4_hash'], unique=False)
    op.create_index(op.f('ix_tbl_1_col_b2_hash'), 'tbl_1', ['col_b2_hash'], unique=False)
    # ### end Alembic commands ###
