"""Generate docs/API.md — every HTTP route, from the application itself.

    venv/bin/python scripts/gen_api_reference.py          # rewrite docs/API.md
    venv/bin/python scripts/gen_api_reference.py --check  # exit 1 if it is stale

The reference is built from the FastAPI app, not written by hand, so it cannot
drift: tests/unit/routes/test_apiReference.py runs `--check` and fails when a
route is added, removed, re-gated or re-limited without regenerating this file.

For each route it records who may call it — read from the dependencies the
route actually declares (`getOfficialUser`, `getAdminUser`, `getCurrentUser`)
— its per-route rate limit as registered with slowapi, and its summary.
"""
import inspect
import os
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "API.md"

# The app needs a full environment to import; the unit-test conftest supplies
# fake values and a mocked database, which is all introspection needs.
sys.path.insert(0, str(ROOT / "tests"))
sys.path.insert(0, str(ROOT / "src"))
os.chdir(ROOT)
import conftest  # noqa: E402,F401
from fastapi.routing import APIRoute  # noqa: E402
from main import app  # noqa: E402
from security.limiter import limiter  # noqa: E402

GATES = [
    ("getOfficialUser", "official"),
    ("getAdminUser", "admin"),
    ("getCurrentUser", "user"),
]


def _dependencyNames(dependant):
    names = set()
    for dep in dependant.dependencies:
        if dep.call is not None:
            names.add(getattr(dep.call, "__name__", ""))
        names |= _dependencyNames(dep)
    return names


def _gate(route: APIRoute) -> str:
    names = _dependencyNames(route.dependant)
    for name, label in GATES:
        if name in names:
            return label
    # Routes that read a bearer token themselves (logout) still need one.
    if "HTTPBearer" in {type(d.call).__name__ for d in route.dependant.dependencies}:
        return "token"
    return "public"


def _limit(route: APIRoute) -> str:
    endpoint = route.endpoint
    key = f"{endpoint.__module__}.{endpoint.__name__}"
    limits = limiter._route_limits.get(key, [])
    return ", ".join(str(l.limit).replace(" per ", "/") for l in limits) or "—"


def _summary(route: APIRoute) -> str:
    text = route.summary or (inspect.getdoc(route.endpoint) or "").split("\n")[0] or route.name
    return text.replace("|", "\\|")


def build() -> str:
    groups = defaultdict(list)
    for route in app.routes:
        if not isinstance(route, APIRoute):
            continue
        tag = (route.tags or ["Other"])[0]
        for method in sorted(route.methods - {"HEAD", "OPTIONS"}):
            groups[tag].append((route.path, method, _gate(route), _limit(route), _summary(route)))

    lines = [
        "# API reference",
        "",
        "<!-- Generated by scripts/gen_api_reference.py — do not edit by hand. -->",
        "",
        "Every HTTP route the backend serves, read from the application itself.",
        "Regenerate with `venv/bin/python scripts/gen_api_reference.py`;",
        "`tests/unit/routes/test_apiReference.py` fails while this file is stale.",
        "",
        "Behind nginx every path is prefixed with `/api` (`/streaks/current` is",
        "`https://noharm.site/api/streaks/current`). The full request and response",
        "schemas are in the OpenAPI document the app serves at `/api/docs`.",
        "",
        "**Who** is the gate the route declares:",
        "",
        "| Who | Meaning |",
        "|-----|---------|",
        "| `public` | No token. |",
        "| `token` | Reads the bearer token itself (logout). |",
        "| `user` | Any signed-in account whose status is not deleted, banned or blocked (`getCurrentUser`). Ownership and visibility are then checked in the service. |",
        "| `admin` | `getAdminUser`: `ADMIN_USER_IDS`, official accounts, or promoted from the app. Anyone else gets 404. |",
        "| `official` | `getOfficialUser`: `OFFICIAL_USER_IDS` only. Anyone else gets 404. |",
        "",
        "**Limit** is the per-route `slowapi` ceiling, per client IP, on top of the",
        "global floor (`RATE_LIMIT_MAX_REQUESTS`, 240/minute).",
        "",
        "The WebSocket (Socket.IO at `/ws/socket.io`) is not an HTTP route; its",
        "events are listed in `docs/FRONTEND_DESIGN_BRIEF.md`, section 9.",
        "",
    ]
    total = sum(len(v) for v in groups.values())
    lines.append(f"{total} routes.")
    lines.append("")
    for tag in sorted(groups):
        lines += [f"## {tag}", "", "| Method | Path | Who | Limit | Summary |", "|---|---|---|---|---|"]
        for path, method, gate, limit, summary in sorted(groups[tag]):
            lines.append(f"| {method} | `{path}` | {gate} | {limit} | {summary} |")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    content = build()
    if "--check" in sys.argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != content:
            print("docs/API.md is stale — run: venv/bin/python scripts/gen_api_reference.py", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(content)
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
